from __future__ import annotations

from forscan_cli import (
    build_parser,
    main,
    print_bulleted_section,
    print_change_plan,
    print_dtc_report,
    print_topic_explanation,
    print_trust_report,
)
from forscan_core import (
    build_trust_report,
    decode_dtc,
    get_topic_explanation,
    infer_system_from_dtc,
    list_abt_files,
    list_topics,
    normalize_dtc,
    normalize_topic,
    parse_abt_bytes,
    parse_abt_file_meta,
    plan_change,
    prompt_user_to_select_file,
    read_abt_file,
    resolve_abt_file,
    serialize_records,
    trust_report_as_json,
    write_csv,
    write_json,
    write_jsonl,
)
from forscan_data import (
    GENERIC_DTC_SYSTEM,
    KNOWN_DTCS,
    OFFICIAL_SOURCES,
    SAFETY_CRITICAL_MODULES,
    TOPIC_EXPLANATIONS,
)
from forscan_models import (
    ABT_CAPTURED_AT_FORMAT,
    ABT_FIELDS,
    EXPLANATION_SEPARATOR,
    AbtFileMeta,
    ChangePlan,
    DtcInfo,
    ParsedRecord,
    SafetyLevel,
    SourceEvidence,
    TopicExplanation,
    TrustReport,
)

__all__ = [
    "ABT_CAPTURED_AT_FORMAT",
    "ABT_FIELDS",
    "EXPLANATION_SEPARATOR",
    "AbtFileMeta",
    "ChangePlan",
    "DtcInfo",
    "GENERIC_DTC_SYSTEM",
    "KNOWN_DTCS",
    "OFFICIAL_SOURCES",
    "ParsedRecord",
    "SAFETY_CRITICAL_MODULES",
    "SafetyLevel",
    "SourceEvidence",
    "TOPIC_EXPLANATIONS",
    "TopicExplanation",
    "TrustReport",
    "build_parser",
    "build_trust_report",
    "decode_dtc",
    "get_topic_explanation",
    "infer_system_from_dtc",
    "list_abt_files",
    "list_topics",
    "main",
    "normalize_dtc",
    "normalize_topic",
    "parse_abt_bytes",
    "parse_abt_file_meta",
    "plan_change",
    "print_bulleted_section",
    "print_change_plan",
    "print_dtc_report",
    "print_topic_explanation",
    "print_trust_report",
    "prompt_user_to_select_file",
    "read_abt_file",
    "resolve_abt_file",
    "serialize_records",
    "trust_report_as_json",
    "write_csv",
    "write_json",
    "write_jsonl",
]


if __name__ == "__main__":
    raise SystemExit(main())
